### ISSUE TITLE
Bug: Cannot mark a meeting for deletion 

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#109]
A meeting was added previously with no issues. The meeting has no street address (not uncommon in Ireland). The "County" or sub_province of the meeting had been filled from a `$meeting_counties_and_sub_provinces` array. Other than that it's a pretty standard meeting entry.

When I try to mark the meeting for deletion via the plugin, I get an error...

`ERROR: Form field "location_sub_province" is required..`

See attached screenshot....

<img width="867" alt="image" src="https://user-images.githubusercontent.com/3714999/200333641-e12772b6-1106-4c14-b0dc-00fcd9ab1216.png">

**Comment by nigel-bmlt** [comment]
could you check for me the setting on configuration page for 'Sub Province':

![image](https://user-images.githubusercontent.com/99465040/200463507-e6ee7b94-ff10-4709-8b14-c9091cc828d6.png)

**Comment by nigel-bmlt** [comment]
fixed in 1.0.10
