### ISSUE TITLE
Feature Request: Submit button feedback

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#114]
Hi!  When submitting a new meeting or a change to a meeting etc, the "Submit Form" button at the end of the page needs to be clicked. It takes a second or tow for the actual form submission to take place before the next sxreen is displayed. During this second or two, there is no feedback that anything is happening, so I have had multiple people smash gthe Submit button a few times..  Is there any chane we could make have a spinner or something that appears immeadiately after the Submit button is pressed? Thgis would stop anyone from smashing the Submit button and sending in multiple forms..

Thanks again,
 Paul

**Comment by nigel-bmlt** [comment]
fixed in 1.0.15
