### ISSUE TITLE
bug: New meeting submitted through bmlt-workflow gets added to the wrong day

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#127]
Hello!  A member submitted a new meeting through the plugin. Everything looked good, after I made one or two small changes in the quickedit dialog, so I approved the meeting. The meeting appeared in the BMLT for Monday (noon), even though the submission was for a Sunday(noon). We don't have any particular setting for anything like "the day the week starts on" in the auto-config.inc.php

bmlt version 3.0.1
plugin version 1.0.18

<img width="833" alt="image" src="https://user-images.githubusercontent.com/3714999/215503037-3d0ec44d-f4a7-4e52-b6b1-f754fdd5fd98.png">

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/3714999/215503622-8b1143f6-d574-4c4f-9a82-6553442bd912.png">

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/3714999/215503748-546cd07e-cfb0-48fd-8e99-e447fdd2dbb4.png">

**Comment by nigel-bmlt** [comment]
BMLT3.x has sunday starting at 0, vs 2.x starting at 1. Thanks for a nice find!

Fixed in 1.0.19
