### ISSUE TITLE
Users dropdown on Service Bodies config page not showing all users

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-workflow#138]
when attempting to add users to the service bodies on `Wordpress Users with Access` section the users dropdown is only displaying 10 users even though my site has 23 users. this actually made for a fun problem, I couldnt add myself as a user and now the configuration page shows `Sorry, you are not allowed to access this page.` even though i (my user) installed and configured the plugin. It does let me still add service body users but atlas my user doesnt show up.

**Comment by tempsaint** [comment]
You should be able to add a user by typing in a username. Does that work?

**Comment by pjaudiomv** [comment]
> You should be able to add a user by typing in a username. Does that work?

No

**Comment by nigel-bmlt** [comment]
@pjaudiomv is this a clean install or an upgrade from an older version?

**Comment by nigel-bmlt** [comment]
if you have wp-cli installed, would you be able to paste the output of:

wp user list      
wp user list-caps <your user>

**Comment by nigel-bmlt** [comment]
Pagination handling problem on the plugin. Will issue a fix for this shortly.

**Comment by nigel-bmlt** [comment]
fixed in 1.0.21
