### ISSUE TITLE
Bug: geolocate fails on good address #14

### ISSUE THREAD

**Issue by nigel-bmlt** [bmlt-enabled/bmlt-workflow#145]
[cdiddy1979](https://github.com/cdiddy1979)

When clicking "approve" in Workflow Submissions, error reads as follows:
"ERROR: Could not geolocate meeting address. Please try amending the address with additional/correct details.."

But the lat/long are filled out, and they are correct.

**Comment by nigel-bmlt** [comment]
Hi [cdiddy1979](https://github.com/cdiddy1979)

Could you please screenshot and attach the options page (showing plugin version, and also the panel that reads auto geolocate root server settings:

![image](https://user-images.githubusercontent.com/99465040/218858563-81cf6547-267e-4695-b27e-1782934af4cf.png)

In addition, could you quickedit the meeting that is failing, then take a screenshot of the quickedit pane.

Thanks

**Comment by cdiddy1979** [comment]
requested screenshots attached, plz let me know how else i can help

![quickedit](https://user-images.githubusercontent.com/47235470/219088213-872a1a6d-3d40-4ee2-8e47-543d5e719e5f.PNG)
![pluginversion](https://user-images.githubusercontent.com/47235470/219088216-b206c7ab-5b0e-44c7-b28e-bc9ca0560bc3.PNG)

**Comment by nigel-bmlt** [comment]
I'm unable to reproduce this one on my side so I'll have to grab some log files to see what is going on.

Are you able to join us on #wordpress-bmlt-workflow on slack https://bmlt.slack.com/ and drop a note and I'll help you troubleshoot further.

Thanks!

**Comment by nigel-bmlt** [comment]
One thing I just thought of - the BMLT server you are connecting to is required to have a valid google maps API key. If your API key is correct, it may be restricted by IP address or header which could also be causing the issue. The Wordpress server will perform a geolocation on the users behalf, so any restrictions would need to include the Wordpress server.

You may be able to check these yourself. Otherwise logs would help diagnose this as well.

**Comment by nigel-bmlt** [comment]
latest version should give a better diagnostic message. please update and retry geolocation, then paste the screenshot. if for some reason the screen contains an api key, just black it out or send it on slack. thanks for helping troubleshoot!

**Comment by nigel-bmlt** [comment]
version 1.0.28 now supports dedicated google maps keys. Please let me know if this addresses your issue:

![image](https://user-images.githubusercontent.com/99465040/221175269-e62d599c-7396-44a2-bb60-75879fbf96eb.png)

**Comment by cdiddy1979** [comment]
thanks!  been out of town for work the last week, will try it out ASAP!

**Comment by nigel-bmlt** [comment]
:) great news!
