### ISSUE TITLE
question about installing setup

### ISSUE THREAD

**Issue by odathp** [bmlt-enabled/bmlt-workflow#147]
Question testing the plugin on a staging site after inputting main server login I get this message "WARNING: Changing the BMLT Root Server settings will remove your service body configuration and existing submissions within the plugin.
Use the BACKUP option before pressing Ok if you do not wish to lose your submissions.
If you press Ok, your service bodies, service body permissions and ALL SUBMISSIONS will be removed.
Are you sure you wish to do this? "

 Question is will this only change my staging site settings or will it also effect something on the server?

**Comment by nigel-bmlt** [comment]
Nothing will be impacted apart from the plugin configuration. The reason this is called out is that service bodies are pretty much the key to the entire installation, and are linked directly to a particular BMLT server. If you change to an entirely different server the only way to reconcile this is to clean the plugin up and start again.
That being said, the information will not show for first time installs in the next version. I'll also change the description to make it a little clearer as to what will be changed and that it only affects this plugin and nothing outside of it (particularly your BMLT configuration)

**Comment by nigel-bmlt** [comment]
text change made to improve this in 1.0.23
