### ISSUE TITLE
Clicking the More Info Button also Selects/Deselects Submissions

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-workflow#151]
Currently, if you select a meeting submission and click the +/- button in the More Info column (of the Workflow Submissions) it causes the submission to be deselected. This seems like a bug. I would think that, after selecting a meeting, we would want the submission to continue to be selected regardless of whether you expand/collapse the more info.

**Comment by tempsaint** [comment]
BTW - I should have added that this could be confusing because if you select a submission, and then click the + for More Info, it deselects the submission and you can't then click the Approve, Reject, or QuickEdit buttons without re-selecting the submission you thought you already selected.

**Comment by nigel-bmlt** [comment]
fixed in 1.0.26
