### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/bmlt-workflow#155]
Can I share you my french translation of meeting_form_update.php for further development?
[meeting_update_form-fr.txt](https://github.com/bmlt-enabled/bmlt-workflow/files/10824817/meeting_update_form-fr.txt)

**Comment by nigel-bmlt** [comment]
absolutely! i will start looking into how to incorporate multi language in a way that makes it easier to keep editing this.

Thank you so much for the support!

**Comment by nigel-bmlt** [comment]
Please see https://github.com/bmlt-enabled/bmlt-workflow/blob/1.0.28-fixes/lang/bmlt-workflow-fr_FR.po for an example of the translation in progress using your content.

I will write up a short wiki page to explain how to edit these files with a tool such as poedit ( https://poedit.net/ )

I will then be able to take pull requests for updates to the language files. Please let me know if you are comfortable with git to do that, otherwise we can get some support for you.

**Comment by Klodd65** [comment]
Thank you so much!
Indeed, I would like poedit to be used for all BMLT applications. It would be much easier for all languages and cultures across NA.
I would encourage them to have an underlying community of developers in NA.

Note: Our regional review and translation subcommittee uses the MateCat Literature Tool.
We pay for the WPML plugin each year to translate the site so that the site is fully bilingual. MateCad users (translators) can participate in the translation of the site. [https://wpml.org/fr/translation-service/matecat/]( https://wpml.org/fr/translation-service/matecat/)

**Comment by nigel-bmlt** [comment]
Translations can now be submitted - pot file for translation is in the /lang directory and scraping the source for translation strings should get all the translatable items. I may have missed some so if you find any that dont translate correctly just raise an issue. Thanks!

**Comment by Klodd65** [comment]
I update the plugin and it works perfectly well!! Just a little things.

**Comment by Klodd65** [comment]
I saw other translation which it need to do. (it's not urgent)
![2023-03-29 12_39_01-Mettre à jour la liste de réunions - CSRQNA _ QRSCNA](https://user-images.githubusercontent.com/3509271/228613695-898e9df1-9a06-43c9-9018-8cc58a624773.png)

**Comment by nigel-bmlt** [comment]
thanks - will update in next release. I will keep this issue open for further changes.

**Comment by nigel-bmlt** [comment]
@Klodd65 would it be possible for you to edit the current po file to make these changes? I'm seeing some there that I'm not sure are correct, but I can't really tell without breaking something. Please let me know if you need a hand on the git side of things.

**Comment by Klodd65** [comment]
Ok, i have 25% done. I will finish it soon.

**Comment by Klodd65** [comment]
About the FSO Feature, is it the WSO who send a First aid kit to the group and if so, can we receive it in French? I prepare some literatures kit for new started groups.  
[FR_2202.pdf](https://github.com/bmlt-enabled/bmlt-workflow/files/11233733/FR_2202.pdf)
[FR_2203.pdf](https://github.com/bmlt-enabled/bmlt-workflow/files/11233734/FR_2203.pdf)
[FR1600.pdf](https://github.com/bmlt-enabled/bmlt-workflow/files/11233735/FR1600.pdf)
[FR3102.pdf](https://github.com/bmlt-enabled/bmlt-workflow/files/11233736/FR3102.pdf)
[Group QuickStart Guide.pdf](https://github.com/bmlt-enabled/bmlt-workflow/files/11233737/Group.QuickStart.Guide.pdf)

**Comment by Klodd65** [comment]
Here is a translation of the [Group QuickStart Guide](https://www.na.org/admin/include/spaw2/uploads/pdf/servicemat/Group%20QuickStart%20Guide.pdf) in French from our Translation Region Subcommittee.
[Group QuickStart Guide FRMODIF.pdf.pdf](https://github.com/bmlt-enabled/bmlt-workflow/files/11241147/Group.QuickStart.Guide.FRMODIF.pdf.pdf)

**Comment by Klodd65** [comment]
Here is a zip file that content the french translation .po file
[Plugin_NZ_NA_English_NZ_TR_FR_CA_TRAD_CTA.zip](https://github.com/bmlt-enabled/bmlt-workflow/files/11241160/Plugin_NZ_NA_English_NZ_TR_FR_CA_TRAD_CTA.zip)
