### ISSUE TITLE
Unable to add Super Admin on Multisite

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-workflow#156]
I regularly log in to do other admin tasks using the superadmin account.
It would be helpful to be able to approve/review workflows while I'm logged in under that user.
However I don't seem to be able to add the superadmin to any of the Service Bodies even though its listed as a user on the site.

**Comment by nigel-bmlt** [comment]
We had a similar feature request on slack to make this implicit for admins. I will also make this implicit for superadmins.

**Comment by kgrimley-bu** [comment]
Thanks @nigel-bmlt I meant to include superadmins but probably didn't due my extended ramblings

**Comment by brustar64** [comment]
Thanks Nigel!

Kind regards,
Bruce

On 28 Feb 2023, at 6:42 am, kgrimley-bu ***@***.***> wrote:

﻿

Thanks @nigel-bmlt<https://github.com/nigel-bmlt> I meant to include superadmins but probably didn't due my extended ramblings

**Comment by nigel-bmlt** [comment]
fixed in 1.0.29

**Comment by tempsaint** [comment]
@nigel-bmlt - this issue is closed and says fixed but I'm a Wordpress Admin and I don't see submissions for a service body if I'm not explicitly added to that service body. Should I be able to see and process all submissions as a Wordpress Admin? This is with version 1.1.13.
