### ISSUE TITLE
New meeting added an additional format

### ISSUE THREAD

**Issue by TheRichWoods** [bmlt-enabled/bmlt-workflow#158]
Just implemented BMLT Workflow on [our site](https://www.longislandna.com/) and it's awesome. However, the first person used it for adding a new meeting, and strangely, it added an additional meeting format code. I'm not sure how that could have happened.

Including screenshots of the submission, and root server history showing that no one else edited it.

![Screenshot 2023-03-03 163652](https://user-images.githubusercontent.com/7906450/222835958-aecaed7f-765e-497c-90cc-7dd6db692ee9.jpg)

![Screenshot 2023-03-03 163320](https://user-images.githubusercontent.com/7906450/222835971-593c2c88-591b-4307-8973-95b7414abac3.jpg)

**Comment by nigel-bmlt** [comment]
Thanks for sending in this report :)

I have a couple of questions
- Is 'Suffolk Area Service Administrator' the user you have configured for the bmlt-workflow plugin to use?
- What happened between March 1 and March 2? In the BMLT history you show creation on 7.49 March 1 and modification at 10pm March 2. If I create a brand new meeting with the plugin on my side, I only see a single history entry.

**Comment by TheRichWoods** [comment]
Yes, that’s the configured user. March 1 was when the meeting was added, and March 2 was when I manually removed the format from the group.On Mar 3, 2023, at 6:07 PM, nigel-bmlt ***@***.***> wrote:﻿
Thanks for sending in this report :)
I have a couple of questions

Is 'Suffolk Area Service Administrator' the user you have configured for the bmlt-workflow plugin to use?
What happened between March 1 and March 2? In the BMLT history you show creation on 7.49 March 1 and modification at 10pm March 2. If I create a brand new meeting with the plugin on my side, I only see a single history entry.

**Comment by nigel-bmlt** [comment]
Ok cool. Could you confirm whether you are using BMLT 2.x or have updated to 3.x.

**Comment by TheRichWoods** [comment]
2.16.6 https://bmlt.newyorkna.org/main_server/

**Comment by nigel-bmlt** [comment]
Thanks. I'm trying to troubleshoot this one but can't seem to reproduce on my end. I suspect where the bug may be however. If you are able to join us on bmlt-enabled slack https://bmlt.slack.com/ channel #wordpress-bmlt-workflow I'd love to grab some debug logs from your wordpress installation if possible.

**Comment by nigel-bmlt** [comment]
Actually I've found it and the fix will be in 1.0.29. Thank you for your assistance and keep an eye out for an upgrade in the next day or so :)
