### ISSUE TITLE
County Field isn't work with Quick Edit Mode

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/bmlt-workflow#171]
I cannot modify and save a county with Quick Edit.

**Comment by nigel-bmlt** [comment]
are your county settings a pull-down in bmlt or a free form field?
what happens when you try to change them on quick edit?

**Comment by Klodd65** [comment]
Nothing. In Quick edit mode, as an example I see a county named A and I would like to change it with "B". I Click Save and the "A" name is remaining.

De : nigel-bmlt ***@***.***>
Envoyé : 22 mars 2023 16:14
À : bmlt-enabled/bmlt-workflow ***@***.***>
Cc : scrti coordonnateur ***@***.***>; Author ***@***.***>
Objet : Re: [bmlt-enabled/bmlt-workflow] County Field isn't work with Quick Edit Mode (Issue #171)


are your county settings a pull-down in bmlt or a free form field?
what happens when you try to change them on quick edit?

-

**Comment by Klodd65** [comment]
I prefer to use counties instead of ASC in a PDF meeting list for newcomers.

**Comment by Klodd65** [comment]
> are your county settings a pull-down in bmlt or a free form field?
> what happens when you try to change them on quick edit?

Can I set counties as a pull-down menu in Workflow. It will avoid mistakes.

**Comment by nigel-bmlt** [comment]
fixed in 1.1.2 - thanks for finding this one.

**Comment by nigel-bmlt** [comment]
> Can you set counties as a pull-down menu in Workflow as a new feature? It will avoid mistakes.

This field depends on the configuration of BMLT - if you use the meeting_counties_and_sub_provinces (or meeting_states_and_provinces)  setting in your BMLT config file, this should be a pull down populated from that list.
