### ISSUE TITLE
Change not recognised - Field change - Extra Location Information

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-workflow#181]
Submitted a change for New Farm Sunday Spirital concepts meeting.
The only change was to remove the additional meeting info about the meeting being closed on Feb 27 but the submission didn't recognise the change despite the change highlighted in yellow.  

Error - Nothing was changed.

![image](https://github.com/bmlt-enabled/bmlt-workflow/assets/29008815/05ae40ac-5cf1-4b62-b860-b03e7ad25e0d)

**Comment by nigel-bmlt** [comment]
fixed in 1.1.10
