### ISSUE TITLE
Request for U/G option to modify group code so that meetings virtual groups can be toggled to publish or unpublish on virtual.na.org

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-workflow#184]
Advice from NAWS below in relation to groups listing/delisting themselves from being globally published.  By default groups are published.

If there is a group that would prefer not to be published on virtual.na.org all you would have to do is simply change the group code from "G" to "U", for example G00004586 would be updated in your BMLT to U00004586.  Then when we pull the data for an update we know to unpublish that meeting on our site.
If the group then decides to republish their meeting information on virtual.na.org they would simply just need their code changed back from "U" to "G" in the BMLT. 

It would be great to be able to add a toggle feature for groups to turn this feature on or off.

**Comment by nigel-bmlt** [comment]
implemented in #1.1.14
