### ISSUE TITLE
Face to Face Meetings with Yes for publish to virtual.na.org option

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-workflow#188]
I'm seeing that all of our meeting updates are coming through with "Publish on virtual.na.org" with "**Yes**" selected, even though the meetings are Face to Face. 

The field correctly only shows up on the end-user form if the meeting is virtual or hybrid. So why is it passing a Yes value when it's a face to face meeting?

**Comment by nigel-bmlt** [comment]
Fixed in 1.1.15
