### ISSUE TITLE
Include link to map on change submission

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-workflow#50]
The purpose of this is to quickly check address entries before approving changes.
1. so we can catch autofill entry mistakes
2. so we can catch non-legitimate requests more easily

Something I though about which may stop autofill entry mistakes is to change the field names from normal "Address" field to "Meeting Address" and maybe it will be less likely to autofill.

**Comment by nigel-bmlt** [comment]
Map display added in 1.0.22
