### ISSUE TITLE
should be using venue_type rather than parsing format list to determine virtual meeting setting

### ISSUE THREAD

**Issue by nigel-bmlt** [bmlt-enabled/bmlt-workflow#63]

**Comment by pjoyce-rd** [comment]
im not concerned but may be worth noting that venue_type field was added in 2.16.4 and the following servers dont support it

[Alaska Region](https://akna.org/bmlt/main_server)
[NA New Jersey](https://www.narcoticsanonymousnj.org/main_server)
[NA Argentina](https://www.na.org.ar/main_server)
[Tri-State Region](https://tsrscna.org/bmlt_dev/main_server)
[NA Sweden](https://www.nasverige.org/main_server)
[Polish Region](https://bmltadmin.anonimowinarkomani.org/main_server)

**Comment by pjaudiomv** [comment]
this encourages people to upgrade, I like it

**Comment by nigel-bmlt** [comment]
I think this calls for a base level check - I personallywon't add support for going back that many revisions  (PRs would be considered ;) , but I'm ok with putting in a 'does not support this version of BMLT'

**Comment by pjaudiomv** [comment]
> I think this calls for a base level check - I personallywon't add support for going back that many revisions (PRs would be considered ;) , but I'm ok with putting in a 'does not support this version of BMLT'

Yes 👍
