### ISSUE TITLE
Starter Kit / FSO issues

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-workflow#77]
I'm sorry if this should be multiple issues. These questions came up during discussion and testing yesterday by documentation group.

We offer a suggestion to allow admins to remove the starter kit question from forms and/or disable this altogether (along with the settings for FSO email address). There are few Service Offices here in the States. 

Another issue would be to be able to set a different FSO address per service body.  Just an example would be my region. We have only one regional website and a regional root server. But no literature distribution (and no starter kits) at the Regional level. Starter kit distribution is handled at the Area service body level and I'm not even sure if all Areas do starter kits at all. This leads back to the first suggestion of having an option to disable the starter kit /FSO functionality in the bmlt-workflow-submission plugin.

**Comment by nigel-bmlt** [comment]
FSO option is now configurable in 0.4.5
<img width="989" alt="fso screenshot" src="https://user-images.githubusercontent.com/99465040/180138384-33c3dc14-2959-47d3-836f-23c7d655057b.png">
