### ISSUE TITLE
Postcode/zipcode format is too restrictive

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#78]
The postcode format in Ireland is different to the format that is enforced in the BMLT Workflow form to submit changes.

The format for postcodes (or eircodes as they are called here) is like P85 FG02, or KH7 T56H etc

Would it be possible to loosen up the format restrictions for postcode/zipcodes? This is a mandatory field, and is presumably used for geo-location, so the inability to enter a valid code has a big knock-on effect.

Thanks!

**Comment by nigel-bmlt** [comment]
changed postcode to free text field. fixed in 0.4.5
