### ISSUE TITLE
Change language in settings from BMLT to BMLT Root Server

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-workflow#81]
I think the language on the button in settings should be changed from BMLT Configuration to BMLT Root Server Configuration.  This would be consistent with other bmlt-enabled plugins (crouton, for sure. I'm actually seeing that bread uses the language BMLT Server - I'll probably open a ticket for that over there as well).  

At this point, BMLT is the overarching platform, not a single tool/application.   

Actually, I'm thinking this language should be changed throughout the plugin where applicable.

**Comment by nigel-bmlt** [comment]
Fixed in 1.0.4 - if I've missed any please add an extra comment here :)
