### ISSUE TITLE
don't mention starter kit in subtext when fso disabled

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-workflow#83]
This is a nit pick but when FSO is disabled when you select new meeting the txt reads `Please fill in the details of your new meeting, and whether your new meeting needs a starter kit provided..` . If FSO is disabled it would be great to not mention starter kit.

<img width="1197" alt="Screen Shot 2022-09-13 at 12 11 13 AM" src="https://user-images.githubusercontent.com/34245618/189834820-29c0fdcf-39b4-4355-9c42-884bf2809f71.png">

**Comment by nigel-bmlt** [comment]
fixed in 1.0.5
