### ISSUE TITLE
Feature Request: Allow the location fields to be renamed

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#91]
A lot of the location field names in BMLT are very "americanised" and dont really make sense outside of the US. I've gotten used to them, and translate them as I go along. But if this "americanised" BMLT terminology is exposed to more members in the Irish fellowship, as it will be through this awesome new plugin, then it would be great if we could localise the terminology.

For example, not many in the general population of the fellowship in Ireland will immeadiatly understand what a `sub province` or a `State` would refer to in an Irish postal address. However they would immeadiatley understand what a `County` or a `Province` was.  Would it be possible to give some configuration options to allow us to rename the fields in the form?

I would like options for the following fields:
Sub Province
State

**Comment by nigel-bmlt** [comment]
Implemented in 1.0.7

![image](https://user-images.githubusercontent.com/99465040/193034100-9ffbb864-b7ff-455d-902e-9b424337f8a6.png)
