### ISSUE TITLE
Feature Request: Allow Meeting Formats to be left blank

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#93]
I find that a lot of the new meetings setup in the Irish fellowship dont have set formats to begin with.
In the plugin the Meeting Formats field is currently a mandatory field, which will causeissues for new groups that havent finalised on any set format yet.
Also, it's pretty common in the Irish fellowship for meetings to not have any declared format at all.
Given all of that, I would appreciate of you make the Meeting Formats section non-mandatory... or configurably non-mandatory.

**Comment by nigel-bmlt** [comment]
implemented in 1.0.7
