### ISSUE TITLE
Either add Venue Type up top or move the Virtual Meeting Options panel

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-workflow#98]
It's natural for users to process the new meeting submission form by columns, top to bottom. As such, they don't get to the Virtual Meeting Options on the top of the second column until after they see required "Location" and "Street Address" fields. If its a virtual meeting these required fields cause confusion.  

So, we're thinking it would be better to either ask right at the top of the first column what the Venue Type is (like the root server does)... this would allow the virtual meeting options to be completely hidden on an In-Person meeting, and vice-versa... allow the Location and Street Address to be hidden on Virtual Only meetings. 

The other option is to just move the Virtual Meeting Options that's already at the top of the second column to the top of the first column. 

Since Venue Type/Virtual Meeting Options dictate some of the Meeting Details, this seems a more important question to answer first.

**Comment by tempsaint** [comment]
Bump

**Comment by nigel-bmlt** [comment]
![image](https://user-images.githubusercontent.com/99465040/212892657-818c56ac-25f8-4e4c-9ee2-c6ffffa86329.png)

![image](https://user-images.githubusercontent.com/99465040/212892763-8982499f-bed1-491a-ba38-e7842bc38aed.png)

does this look like it would do the trick?

**Comment by tempsaint** [comment]
I believe so. Thanks.

**Comment by nigel-bmlt** [comment]
fixed in 1.0.17
